### ISSUE TITLE
Error Logging in

### ISSUE THREAD

**Issue by TJJP** [wiorca/docker-windscribe#6]
I am trying to set up the docker, but I keep getting this error message: 
usermod: no changes
Starting windscribe ... OK
spawn windscribe login
Windscribe Username: vtviugslytzyhcfqju
Windscribe Password: 
API Error: No API Connectivity

Is this a bug or am I doing something wrong?

Thanks!

**Comment by wiorca** [comment]
So it looks like the service isn't running yet.  So I think it's a race condition.

**Comment by TJJP** [comment]
How can I fix it?
